In [2]:
import pandas as pd
import math
import numpy as np

In [15]:
df = pd.read_csv("Flights_mergedSUM_Degrees.csv")
df.head(50)

,Id,Label,name,city,country,iata,icao,latitude,longitude,alt,...,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality
0,1,NaN,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,...,4,4,8,5,5,10,9,0.228983,0.239638,0.000000
1,2,NaN,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,...,7,7,14,8,8,16,9,0.229033,0.240114,7.333333
2,3,NaN,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,...,9,8,17,12,10,22,9,0.229050,0.240273,18.666667
3,4,NaN,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,...,9,9,18,11,11,22,9,0.229067,0.240432,20.500000
4,5,NaN,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,...,32,32,64,47,48,95,8,0.296876,0.321212,148499.265484
5,6,NaN,Wewak International Airport,Wewak,Papua New Guinea,WWK,AYWK,-3.583830,143.669006,19,...,4,4,8,6,6,12,9,0.228983,0.239638,0.666667
6,7,NaN,Narsarsuaq Airport,Narssarssuaq,Greenland,UAK,BGBW,61.160500,-45.425999,112,...,5,5,10,5,5,10,9,0.215450,0.223469,25251.425263
7,8,NaN,Godthaab / Nuuk Airport,Godthaab,Greenland,GOH,BGGH,64.190903,-51.678101,283,...,8,8,16,8,8,16,8,0.249089,0.262158,52487.942977
8,9,NaN,Kangerlussuaq Airport,Sondrestrom,Greenland,SFJ,BGSF,67.012222,-50.711603,165,...,7,7,14,7,7,14,8,0.270368,0.285776,67328.393305
9,10,NaN,Thule Air Base,Thule,Greenland,THU,BGTL,76.531197,-68.703201,251,...,1,1,2,1,1,2,12,0.130925,0.132874,0.000000
10,11,NaN,Akureyri Airport,Akureyri,Iceland,AEY,BIAR,65.660004,-18.072701,6,...,1,1,2,1,1,2,10,0.166332,0.170250,0.000000
11,12,NaN,Egilsstaðir Airport,Egilsstadir,Iceland,EGS,BIEG,65.283302,-14.401400,76,...,1,1,2,1,1,2,10,0.166332,0.170250,0.000000
12,15,NaN,Ísafjörður Airport,Isafjordur,Iceland,IFJ,BIIS,66.058098,-23.135300,8,...,1,1,2,1,1,2,10,0.166332,0.170250,0.000000
13,16,NaN,Keflavik International Airport,Keflavik,Iceland,KEF,BIKF,63.985001,-22.605600,171,...,34,32,66,46,45,91,7,0.330289,0.359413,69690.425799
14,18,NaN,Reykjavik Airport,Reykjavik,Iceland,RKV,BIRK,64.129997,-21.940599,48,...,4,4,8,4,4,8,9,0.199505,0.206475,18864.000000
15,21,NaN,Sault Ste Marie Airport,Sault Sainte Marie,Canada,YAM,CYAM,46.485001,-84.509399,630,...,4,4,8,4,4,8,8,0.282939,0.297414,9.062679
16,24,NaN,St. Anthony Airport,St. Anthony,Canada,YAY,CYAY,51.391899,-56.083099,108,...,3,3,6,3,3,6,9,0.233660,0.242532,3753.130416
17,27,NaN,Baie Comeau Airport,Baie Comeau,Canada,YBC,CYBC,49.132500,-68.204399,71,...,4,4,8,6,6,12,8,0.263021,0.276845,1.458077
18,28,NaN,CFB Bagotville,Bagotville,Canada,YBG,CYBG,48.330601,-70.996399,522,...,4,4,8,4,4,8,8,0.262956,0.276776,213.295221
19,29,NaN,Baker Lake Airport,Baker Lake,Canada,YBK,CYBK,64.298897,-96.077797,59,...,3,4,7,6,6,12,10,0.190470,0.196775,1.666667
20,30,NaN,Campbell River Airport,Campbell River,Canada,YBL,CYBL,49.950802,-125.271004,346,...,3,3,6,6,6,12,9,0.264237,0.276951,3155.684150
21,31,NaN,Brandon Municipal Airport,Brandon,Canada,YBR,CYBR,49.910000,-99.951897,1343,...,1,1,2,1,1,2,9,0.254881,0.265932,0.000000
22,32,NaN,Cambridge Bay Airport,Cambridge Bay,Canada,YCB,CYCB,69.108101,-105.138000,90,...,4,4,8,6,6,12,10,0.205366,0.212672,5.333333
23,33,NaN,Nanaimo Airport,Nanaimo,Canada,YCD,CYCD,49.054970,-123.869863,92,...,2,2,4,2,2,4,9,0.265822,0.278834,0.000000
24,34,NaN,Castlegar/West Kootenay Regional Airport,Castlegar,Canada,YCG,CYCG,49.296398,-117.632004,1624,...,2,2,4,2,2,4,9,0.265822,0.278834,0.000000
25,36,NaN,Charlo Airport,Charlo,Canada,YCL,CYCL,47.990799,-66.330299,132,...,2,2,4,2,2,4,9,0.240557,0.251101,2.041579
26,37,NaN,Kugluktuk Airport,Coppermine,Canada,YCO,CYCO,67.816704,-115.143997,74,...,3,3,6,5,5,10,10,0.205420,0.212699,9416.333333
27,40,NaN,Clyde River Airport,Clyde River,Canada,YCY,CYCY,70.486099,-68.516701,87,...,2,2,4,4,4,8,10,0.196551,0.202671,3143.000000
28,41,NaN,Coral Harbour Airport,Coral Harbour,Canada,YZS,CYZS,64.193298,-83.359398,210,...,4,4,8,5,6,11,10,0.190482,0.196828,52.121669
29,45,NaN,Deer Lake Airport,Deer Lake,Canada,YDF,CYDF,49.210800,-57.391399,72,...,5,4,9,8,7,15,8,0.283015,0.297616,5990.305436
30,48,NaN,Dawson Creek Airport,Dawson Creek,Canada,YDQ,CYDQ,55.742298,-120.182999,2148,...,2,2,4,2,2,4,9,0.264214,0.276792,1363.810493
31,49,NaN,Edmonton International Airport,Edmonton,Canada,YEG,CYEG,53.309700,-113.580002,2373,...,37,38,75,71,68,139,8,0.325740,0.350793,65977.956204
32,50,NaN,Arviat Airport,Eskimo Point,Canada,YEK,CYEK,61.094200,-94.070801,32,...,3,3,6,7,7,14,10,0.190459,0.196616,1.333333
33,54,NaN,Inuvik Mike Zubko Airport,Inuvik,Canada,YEV,CYEV,68.304199,-133.483002,224,...,7,7,14,8,8,16,11,0.170589,0.175873,22012.666667
34,55,NaN,Iqaluit Airport,Iqaluit,Canada,YFB,CYFB,63.756402,-68.555801,110,...,10,10,20,18,18,36,9,0.244577,0.256794,69782.256630
35,56,NaN,Fredericton Airport,Fredericton,Canada,YFC,CYFC,45.868900,-66.537201,68,...,4,4,8,4,4,8,8,0.286521,0.301634,0.000000
36,58,NaN,Flin Flon Airport,Flin Flon,Canada,YFO,CYFO,54.678101,-101.681999,997,...,3,3,6,5,4,9,9,0.233591,0.243172,0.000000
37,60,NaN,Fort Simpson Airport,Fort Simpson,Canada,YFS,CYFS,61.760201,-121.237000,555,...,1,1,2,2,2,4,10,0.205299,0.212116,0.000000
38,61,NaN,Kingston Norman Rogers Airport,Kingston,Canada,YGK,CYGK,44.225300,-76.596901,305,...,1,1,2,1,1,2,8,0.282228,0.296138,0.000000
39,62,NaN,La Grande Rivière Airport,La Grande Riviere,Canada,YGL,CYGL,53.625301,-77.704201,639,...,3,3,6,3,3,6,8,0.262912,0.276537,11369.078470
40,63,NaN,Gaspé (Michel-Pouliot) Airport,Gaspe,Canada,YGP,CYGP,48.775299,-64.478600,112,...,2,2,4,2,2,4,8,0.237721,0.246907,0.000000
41,65,NaN,Îles-de-la-Madeleine Airport,Iles De La Madeleine,Canada,YGR,CYGR,47.424702,-61.778099,35,...,3,3,6,3,3,6,8,0.237757,0.247118,150.738986
42,67,NaN,Dryden Regional Airport,Dryden,Canada,YHD,CYHD,49.831699,-92.744202,1354,...,3,4,7,3,4,7,9,0.221784,0.230060,55.466667
43,68,NaN,Ulukhaktok Holman Airport,Holman Island,Canada,YHI,CYHI,70.762802,-117.806000,117,...,3,3,6,3,3,6,11,0.170552,0.175237,3153.333333
44,69,NaN,Gjoa Haven Airport,Gjoa Haven,Canada,YHK,CYHK,68.635597,-95.849701,152,...,3,3,6,5,4,9,10,0.205326,0.212434,0.000000
45,70,NaN,John C. Munro Hamilton International Airport,Hamilton,Canada,YHM,CYHM,43.173599,-79.934998,780,...,4,4,8,4,4,8,9,0.256628,0.268802,13.968048
46,71,NaN,Montréal / Saint-Hubert Airport,Montreal,Canada,YHU,CYHU,45.517502,-73.416901,90,...,4,4,8,4,4,8,8,0.238207,0.247974,58.101299
47,72,NaN,Hay River / Merlyn Carter Airport,Hay River,Canada,YHY,CYHY,60.839699,-115.782997,541,...,3,3,6,3,3,6,9,0.246282,0.256854,0.000000
48,73,NaN,Halifax / Stanfield International Airport,Halifax,Canada,YHZ,CYHZ,44.880798,-63.508598,477,...,33,28,61,52,43,95,8,0.316117,0.340932,49856.672461
49,75,NaN,Pond Inlet Airport,Pond Inlet,Canada,YIO,CYIO,72.683296,-77.966698,181,...,2,2,4,3,3,6,11,0.164299,0.168055,1.000000

In [4]:
df.describe()

,Id,Label,latitude,longitude,alt,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality
count,3147.000000,0.0,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000
mean,3576.896409,NaN,25.817445,3.425252,996.084207,11.698761,11.698761,23.397521,21.188116,21.188116,42.376231,8.656498,0.259067,0.274919,9340.054020
std,2315.779158,NaN,27.764499,90.669891,1740.382501,24.908456,24.980071,49.883430,55.179337,55.264873,110.437920,0.791659,0.041494,0.048845,43132.734951
min,1.000000,NaN,-54.843300,-179.876999,-72.000000,1.000000,1.000000,2.000000,1.000000,1.000000,2.000000,7.000000,0.117349,0.118753,0.000000
25%,1757.000000,NaN,6.942539,-77.197452,48.000000,2.000000,2.000000,4.000000,2.000000,2.000000,4.000000,8.000000,0.234077,0.244445,0.000000
50%,3271.000000,NaN,32.898102,9.604000,262.000000,3.000000,3.000000,6.000000,4.000000,4.000000,8.000000,9.000000,0.260452,0.274720,1.656687
75%,5670.500000,NaN,46.177900,79.901352,1083.000000,9.000000,9.000000,18.000000,13.000000,13.000000,26.000000,9.000000,0.286365,0.305267,1112.051270
max,11922.000000,NaN,78.246101,179.341003,14472.000000,238.000000,239.000000,477.000000,911.000000,915.000000,1826.000000,13.000000,0.414766,0.466609,634112.601426

On average, an airport has how many outgoing flights? -> average weighted outdegree: 21.188
And to how many diferent airports? -> average outdegree: 11.699

In [5]:
df["outdegree"].mean()

np.float64(11.698760724499524)

In [6]:
df[df["Id"] == 3830]

,Id,Label,name,city,country,iata,icao,latitude,longitude,alt,...,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality
1867,3830,NaN,Chicago O'Hare International Airport,Chicago,United States,ORD,KORD,41.9786,-87.9048,672,...,203,205,408,550,557,1107,7,0.388491,0.436327,457824.881245

In [7]:
df[df["Id"] == 3682]

,Id,Label,name,city,country,iata,icao,latitude,longitude,alt,...,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality
1792,3682,NaN,Hartsfield Jackson Atlanta International Airport,Atlanta,United States,ATL,KATL,33.6367,-84.428101,1026,...,216,217,433,911,915,1826,7,0.375911,0.427594,306637.099759

In [8]:
df_edges = pd.read_csv("Flights_mergedSUM_Edges.csv")
df_edges.head()

,Source,Target,Type,Id,Label,Weight,airline,aid,s,d,codeshare,stops,equipment
0,2965,2990,Directed,270652,NaN,1,2B,410,AER,KZN,NaN,0,CR2
1,2966,2990,Directed,270653,NaN,1,2B,410,ASF,KZN,NaN,0,CR2
2,2966,2962,Directed,270654,NaN,1,2B,410,ASF,MRV,NaN,0,CR2
3,2968,2990,Directed,270655,NaN,1,2B,410,CEK,KZN,NaN,0,CR2
4,2968,4078,Directed,270656,NaN,2,2G,1654,CEK,OVB,NaN,0,A81

In [9]:
df_edges_sorted = df_edges.sort_values(by="Weight", ascending=False)
df_edges_sorted.head()

,Source,Target,Type,Id,Label,Weight,airline,aid,s,d,codeshare,stops,equipment
5558,3830,3682,Directed,276882,NaN,20,VS,5347,ORD,ATL,Y,0,717 M88 319
4066,3682,3830,Directed,275354,NaN,19,VS,5347,ATL,ORD,Y,0,757 319 320 M90 M88 717
2685,3179,3885,Directed,273623,NaN,13,TG,4940,HKT,BKK,Y,0,333 744 330 AB6 773 747 320
5631,3830,3861,Directed,276955,NaN,13,US,5265,ORD,MSY,Y,0,E75
4065,3682,3576,Directed,275353,NaN,12,VS,5347,ATL,MIA,Y,0,757 320

In [10]:
df_edges_sorted["Source_name"] = df_edges_sorted["Source"].map(df.set_index("Id")["name"])
df_edges_sorted

,Source,Target,Type,Id,Label,Weight,airline,aid,s,d,codeshare,stops,equipment,Source_name
5558,3830,3682,Directed,276882,NaN,20,VS,5347,ORD,ATL,Y,0,717 M88 319,Chicago O'Hare International Airport
4066,3682,3830,Directed,275354,NaN,19,VS,5347,ATL,ORD,Y,0,757 319 320 M90 M88 717,Hartsfield Jackson Atlanta International Airport
2685,3179,3885,Directed,273623,NaN,13,TG,4940,HKT,BKK,Y,0,333 744 330 AB6 773 747 320,Phuket International Airport
5631,3830,3861,Directed,276955,NaN,13,US,5265,ORD,MSY,Y,0,E75,Chicago O'Hare International Airport
4065,3682,3576,Directed,275353,NaN,12,VS,5347,ATL,MIA,Y,0,757 320,Hartsfield Jackson Atlanta International Airport
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36811,3330,6337,Directed,338305,NaN,1,ZL,4178,TSV,WIN,NaN,0,SF3,Townsville Airport
36812,3363,3339,Directed,338306,NaN,1,ZL,4178,WGA,MEL,NaN,0,SF3,Wagga Wagga City Airport
36813,6337,6289,Directed,338308,NaN,1,ZL,4178,WIN,LRE,NaN,0,SF3,Winton Airport
36814,6337,3330,Directed,338309,NaN,1,ZL,4178,WIN,TSV,NaN,0,SF3,Winton Airport
36815,6334,3341,Directed,338310,NaN,1,ZL,4178,WYA,ADL,NaN,0,SF3,Whyalla Airport

In [11]:
df_edges_sorted["Target_name"] = df_edges_sorted["Target"].map(df.set_index("Id")["name"])
df_edges_sorted

,Source,Target,Type,Id,Label,Weight,airline,aid,s,d,codeshare,stops,equipment,Source_name,Target_name
5558,3830,3682,Directed,276882,NaN,20,VS,5347,ORD,ATL,Y,0,717 M88 319,Chicago O'Hare International Airport,Hartsfield Jackson Atlanta International Airport
4066,3682,3830,Directed,275354,NaN,19,VS,5347,ATL,ORD,Y,0,757 319 320 M90 M88 717,Hartsfield Jackson Atlanta International Airport,Chicago O'Hare International Airport
2685,3179,3885,Directed,273623,NaN,13,TG,4940,HKT,BKK,Y,0,333 744 330 AB6 773 747 320,Phuket International Airport,Suvarnabhumi Airport
5631,3830,3861,Directed,276955,NaN,13,US,5265,ORD,MSY,Y,0,E75,Chicago O'Hare International Airport,Louis Armstrong New Orleans International Airport
4065,3682,3576,Directed,275353,NaN,12,VS,5347,ATL,MIA,Y,0,757 320,Hartsfield Jackson Atlanta International Airport,Miami International Airport
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36811,3330,6337,Directed,338305,NaN,1,ZL,4178,TSV,WIN,NaN,0,SF3,Townsville Airport,Winton Airport
36812,3363,3339,Directed,338306,NaN,1,ZL,4178,WGA,MEL,NaN,0,SF3,Wagga Wagga City Airport,Melbourne International Airport
36813,6337,6289,Directed,338308,NaN,1,ZL,4178,WIN,LRE,NaN,0,SF3,Winton Airport,Longreach Airport
36814,6337,3330,Directed,338309,NaN,1,ZL,4178,WIN,TSV,NaN,0,SF3,Winton Airport,Townsville Airport
36815,6334,3341,Directed,338310,NaN,1,ZL,4178,WYA,ADL,NaN,0,SF3,Whyalla Airport,Adelaide International Airport

In [12]:
df_top5 = df_edges_sorted.nlargest(30, "Weight")
df_top5

,Source,Target,Type,Id,Label,Weight,airline,aid,s,d,codeshare,stops,equipment,Source_name,Target_name
5558,3830,3682,Directed,276882,NaN,20,VS,5347,ORD,ATL,Y,0,717 M88 319,Chicago O'Hare International Airport,Hartsfield Jackson Atlanta International Airport
4066,3682,3830,Directed,275354,NaN,19,VS,5347,ATL,ORD,Y,0,757 319 320 M90 M88 717,Hartsfield Jackson Atlanta International Airport,Chicago O'Hare International Airport
2685,3179,3885,Directed,273623,NaN,13,TG,4940,HKT,BKK,Y,0,333 744 330 AB6 773 747 320,Phuket International Airport,Suvarnabhumi Airport
5631,3830,3861,Directed,276955,NaN,13,US,5265,ORD,MSY,Y,0,E75,Chicago O'Hare International Airport,Louis Armstrong New Orleans International Airport
4065,3682,3576,Directed,275353,NaN,12,VS,5347,ATL,MIA,Y,0,757 320,Hartsfield Jackson Atlanta International Airport,Miami International Airport
8250,3370,3386,Directed,279903,NaN,12,ZH,4611,CAN,HGH,Y,0,737 320,Guangzhou Baiyun International Airport,Hangzhou Xiaoshan International Airport
4969,3797,507,Directed,276275,NaN,12,VS,5347,JFK,LHR,Y,0,333 346 744,John F Kennedy International Airport,London Heathrow Airport
13877,3885,3077,Directed,288476,NaN,12,UL,4349,BKK,HKG,Y,0,332,Suvarnabhumi Airport,Hong Kong International Airport
4078,2179,2194,Directed,275367,NaN,12,WY,3778,AUH,MCT,Y,0,ATR E75 738 73G,Abu Dhabi International Airport,Muscat International Airport
13910,3077,3885,Directed,288529,NaN,12,UL,4349,HKG,BKK,Y,0,332,Hong Kong International Airport,Suvarnabhumi Airport
4701,11051,2057,Directed,275997,NaN,12,WY,3778,DOH,BAH,Y,0,738,Hamad International Airport,Bahrain International Airport
5337,3576,3682,Directed,276655,NaN,12,VS,5347,MIA,ATL,Y,0,M88 757 M90 73H,Miami International Airport,Hartsfield Jackson Atlanta International Airport
5187,507,3797,Directed,276501,NaN,12,VS,5347,LHR,JFK,Y,0,346 744 333,London Heathrow Airport,John F Kennedy International Airport
5059,3484,507,Directed,276368,NaN,11,VS,5347,LAX,LHR,Y,0,346 343 744,Los Angeles International Airport,London Heathrow Airport
8528,1005,907,Directed,280226,NaN,11,TK,4951,HRE,LUN,Y,0,788,Robert Gabriel Mugabe International Airport,Kenneth Kaunda International Airport Lusaka
3161,3861,3797,Directed,274248,NaN,11,VS,5347,MSY,JFK,Y,0,CR9,Louis Armstrong New Orleans International Airport,John F Kennedy International Airport
8422,3931,3885,Directed,280095,NaN,11,TG,4940,CNX,BKK,Y,0,AB6 747 734 320 333 773 777,Chiang Mai International Airport,Suvarnabhumi Airport
7016,3751,3682,Directed,278520,NaN,11,WN,4547,DEN,ATL,Y,0,73W,Denver International Airport,Hartsfield Jackson Atlanta International Airport
4948,3797,1382,Directed,276253,NaN,11,US,5265,JFK,CDG,Y,0,763 757,John F Kennedy International Airport,Charles de Gaulle International Airport
3151,3797,3861,Directed,274238,NaN,11,VS,5347,JFK,MSY,Y,0,CR9,John F Kennedy International Airport,Louis Armstrong New Orleans International Airport
4220,1382,3797,Directed,275511,NaN,11,US,5265,CDG,JFK,Y,0,763 757,Charles de Gaulle International Airport,John F Kennedy International Airport
4063,3682,3670,Directed,275351,NaN,11,VS,5347,ATL,DFW,Y,0,M88 738,Hartsfield Jackson Atlanta International Airport,Dallas Fort Worth International Airport
6971,3682,3751,Directed,278467,NaN,11,WN,4547,ATL,DEN,Y,0,73W,Hartsfield Jackson Atlanta International Airport,Denver International Airport
8820,3469,3682,Directed,280589,NaN,11,WN,4547,SFO,ATL,Y,0,73W,San Francisco International Airport,Hartsfield Jackson Atlanta International Airport
5302,2194,2179,Directed,276619,NaN,11,WY,3778,MCT,AUH,Y,0,ATR E75 738 73G,Muscat International Airport,Abu Dhabi International Airport
5192,507,3484,Directed,276506,NaN,11,VS,5347,LHR,LAX,Y,0,346 343 744,London Heathrow Airport,Los Angeles International Airport
7087,1165,1187,Directed,278595,NaN,11,WB,4292,KGL,EBB,Y,0,CRJ 738 DH4,Kigali International Airport,Entebbe International Airport
6195,3361,2006,Directed,277527,NaN,11,VA,5360,SYD,AKL,Y,0,763 73H 320 772,Sydney Kingsford Smith International Airport,Auckland International Airport
626,3393,3379,Directed,271304,NaN,10,ZH,4611,CKG,XIY,Y,0,737,Chongqing Jiangbei International Airport,Xi'an Xianyang International Airport
8559,3304,3275,Directed,280267,NaN,10,QZ,2857,KUL,CGK,Y,0,320,Kuala Lumpur International Airport,Soekarno-Hatta International Airport

In [13]:
df_top5[["Weight","Source_name", "Target_name"]]

,Weight,Source_name,Target_name
5558,20,Chicago O'Hare International Airport,Hartsfield Jackson Atlanta International Airport
4066,19,Hartsfield Jackson Atlanta International Airport,Chicago O'Hare International Airport
2685,13,Phuket International Airport,Suvarnabhumi Airport
5631,13,Chicago O'Hare International Airport,Louis Armstrong New Orleans International Airport
4065,12,Hartsfield Jackson Atlanta International Airport,Miami International Airport
8250,12,Guangzhou Baiyun International Airport,Hangzhou Xiaoshan International Airport
4969,12,John F Kennedy International Airport,London Heathrow Airport
13877,12,Suvarnabhumi Airport,Hong Kong International Airport
4078,12,Abu Dhabi International Airport,Muscat International Airport
13910,12,Hong Kong International Airport,Suvarnabhumi Airport
4701,12,Hamad International Airport,Bahrain International Airport
5337,12,Miami International Airport,Hartsfield Jackson Atlanta International Airport
5187,12,London Heathrow Airport,John F Kennedy International Airport
5059,11,Los Angeles International Airport,London Heathrow Airport
8528,11,Robert Gabriel Mugabe International Airport,Kenneth Kaunda International Airport Lusaka
3161,11,Louis Armstrong New Orleans International Airport,John F Kennedy International Airport
8422,11,Chiang Mai International Airport,Suvarnabhumi Airport
7016,11,Denver International Airport,Hartsfield Jackson Atlanta International Airport
4948,11,John F Kennedy International Airport,Charles de Gaulle International Airport
3151,11,John F Kennedy International Airport,Louis Armstrong New Orleans International Airport
4220,11,Charles de Gaulle International Airport,John F Kennedy International Airport
4063,11,Hartsfield Jackson Atlanta International Airport,Dallas Fort Worth International Airport
6971,11,Hartsfield Jackson Atlanta International Airport,Denver International Airport
8820,11,San Francisco International Airport,Hartsfield Jackson Atlanta International Airport
5302,11,Muscat International Airport,Abu Dhabi International Airport
5192,11,London Heathrow Airport,Los Angeles International Airport
7087,11,Kigali International Airport,Entebbe International Airport
6195,11,Sydney Kingsford Smith International Airport,Auckland International Airport
626,10,Chongqing Jiangbei International Airport,Xi'an Xianyang International Airport
8559,10,Kuala Lumpur International Airport,Soekarno-Hatta International Airport

In [33]:
df1 = pd.read_csv("Flights_norm.csv")
df1

,Id,Label,name,city,country,iata,icao,latitude,longitude,alt,...,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality
0,1,NaN,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,...,4,4,8,5,5,10,9,0.228983,0.239638,0.000000
1,2,NaN,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,...,7,7,14,8,8,16,9,0.229033,0.240114,0.000001
2,3,NaN,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,...,9,8,17,12,10,22,9,0.229050,0.240273,0.000002
3,4,NaN,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,...,9,9,18,11,11,22,9,0.229067,0.240432,0.000002
4,5,NaN,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,...,32,32,64,47,48,95,8,0.296876,0.321212,0.015009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3142,11258,NaN,Saumlaki/Olilit Airport,Saumlaki,Indonesia,SXK,WAPI,-7.988610,131.306000,218,...,1,1,2,1,1,2,11,0.164248,0.168398,0.000000
3143,11436,NaN,Tarko-Sale Airport,Tarko-Sale,Russia,TQL,USDS,64.930801,77.818100,82,...,1,1,2,1,1,2,10,0.208745,0.217677,0.000000
3144,11473,NaN,Jinchuan Airport,Jinchuan,China,JIC,ZLJC,38.542222,102.348333,4740,...,4,4,8,6,6,12,9,0.231545,0.245423,0.000001
3145,11498,NaN,Alashankou Bole (Bortala) airport,Bole,China,BPL,ZWAX,44.895000,82.300000,1253,...,1,1,2,1,1,2,9,0.235092,0.247446,0.000000
3146,11922,NaN,Iwakuni Marine Corps Air Station,Iwakuni,Japan,IWK,RJOI,34.143902,132.235992,7,...,1,1,2,1,1,2,9,0.257152,0.269162,0.000000

In [34]:
df1_sorted = df1.sort_values(by="betweenesscentrality", ascending=False)
df1_sorted.head(6)

,Id,Label,name,city,country,iata,icao,latitude,longitude,alt,...,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality
626,1382,NaN,Charles de Gaulle International Airport,Paris,France,CDG,LFPG,49.012798,2.550000,392,...,232,237,469,516,524,1040,7,0.411726,0.464461,0.064090
1698,3484,NaN,Los Angeles International Airport,Los Angeles,United States,LAX,KLAX,33.942501,-118.407997,125,...,147,148,295,497,489,986,7,0.397825,0.438457,0.062142
1006,2188,NaN,Dubai International Airport,Dubai,United Arab Emirates,DXB,OMDB,25.252800,55.364399,62,...,179,185,364,348,350,698,7,0.404266,0.451291,0.060087
191,340,NaN,Frankfurt am Main Airport,Frankfurt,Germany,FRA,EDDF,50.033333,8.570556,364,...,238,239,477,493,497,990,7,0.414766,0.466609,0.054225
1843,3774,NaN,Ted Stevens Anchorage International Airport,Anchorage,United States,ANC,PANC,61.174400,-149.996002,152,...,34,34,68,59,59,118,8,0.301919,0.326639,0.052764
1628,3364,NaN,Beijing Capital International Airport,Beijing,China,PEK,ZBAA,40.080101,116.584999,116,...,204,204,408,530,531,1061,7,0.389356,0.441109,0.051084

In [29]:
df1_sorted.head(30)

,Id,Label,name,city,country,iata,icao,latitude,longitude,alt,...,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality
626,1382,NaN,Charles de Gaulle International Airport,Paris,France,CDG,LFPG,49.012798,2.550000,392,...,232,237,469,516,524,1040,7,0.411726,0.464461,0.064090
1698,3484,NaN,Los Angeles International Airport,Los Angeles,United States,LAX,KLAX,33.942501,-118.407997,125,...,147,148,295,497,489,986,7,0.397825,0.438457,0.062142
1006,2188,NaN,Dubai International Airport,Dubai,United Arab Emirates,DXB,OMDB,25.252800,55.364399,62,...,179,185,364,348,350,698,7,0.404266,0.451291,0.060087
191,340,NaN,Frankfurt am Main Airport,Frankfurt,Germany,FRA,EDDF,50.033333,8.570556,364,...,238,239,477,493,497,990,7,0.414766,0.466609,0.054225
1843,3774,NaN,Ted Stevens Anchorage International Airport,Anchorage,United States,ANC,PANC,61.174400,-149.996002,152,...,34,34,68,59,59,118,8,0.301919,0.326639,0.052764
1628,3364,NaN,Beijing Capital International Airport,Beijing,China,PEK,ZBAA,40.080101,116.584999,116,...,204,204,408,530,531,1061,7,0.389356,0.441109,0.051084
1867,3830,NaN,Chicago O'Hare International Airport,Chicago,United States,ORD,KORD,41.978600,-87.904800,672,...,203,205,408,550,557,1107,7,0.388491,0.436327,0.046272
125,193,NaN,Lester B. Pearson International Airport,Toronto,Canada,YYZ,CYYZ,43.677200,-79.630600,569,...,146,147,293,317,319,636,7,0.393152,0.434931,0.045887
282,580,NaN,Amsterdam Airport Schiphol,Amsterdam,Netherlands,AMS,EHAM,52.308601,4.763890,-11,...,231,232,463,450,453,903,7,0.404162,0.456480,0.045717
766,1701,NaN,Atatürk International Airport,Istanbul,Turkey,ISL,LTBA,40.976898,28.814600,163,...,227,224,451,357,354,711,7,0.391294,0.444375,0.043056
1178,2564,NaN,Guarulhos - Governador André Franco Montoro In...,Sao Paulo,Brazil,GRU,SBGR,-23.435556,-46.473057,2459,...,90,92,182,194,193,387,7,0.359296,0.397957,0.042524
255,507,NaN,London Heathrow Airport,London,United Kingdom,LHR,EGLL,51.470600,-0.461941,83,...,170,170,340,522,525,1047,7,0.409849,0.454663,0.039605
1047,2279,NaN,Narita International Airport,Tokyo,Japan,NRT,RJAA,35.764702,140.386002,141,...,103,103,206,289,286,575,7,0.386107,0.426016,0.036145
1625,3361,NaN,Sydney Kingsford Smith International Airport,Sydney,Australia,SYD,YSSY,-33.946098,151.177002,21,...,83,85,168,202,208,410,8,0.349750,0.385608,0.035651
1594,3316,NaN,Singapore Changi Airport,Singapore,Singapore,SIN,WSSS,1.350190,103.994003,22,...,124,124,248,409,405,814,8,0.362986,0.408340,0.031987
1597,3320,NaN,Brisbane International Airport,Brisbane,Australia,BNE,YBBN,-27.384199,153.117004,13,...,55,59,114,143,151,294,8,0.329666,0.359612,0.031930
1737,3577,NaN,Seattle Tacoma International Airport,Seattle,United States,SEA,KSEA,47.449001,-122.308998,433,...,93,90,183,201,201,402,7,0.364669,0.399702,0.031548
1792,3682,NaN,Hartsfield Jackson Atlanta International Airport,Atlanta,United States,ATL,KATL,33.636700,-84.428101,1026,...,216,217,433,911,915,1826,7,0.375911,0.427594,0.030992
1996,4029,NaN,Domodedovo International Airport,Moscow,Russia,DME,UUDD,55.408798,37.906300,588,...,188,187,375,324,322,646,8,0.352138,0.402171,0.030966
1472,3077,NaN,Hong Kong International Airport,Hong Kong,Hong Kong,HKG,VHHH,22.308901,113.915001,28,...,133,132,265,354,354,708,7,0.381703,0.426125,0.029768
89,146,NaN,Montreal / Pierre Elliott Trudeau Internationa...,Montreal,Canada,YUL,CYUL,45.470600,-73.740799,118,...,92,93,185,186,185,371,7,0.356084,0.392825,0.029522
1924,3930,NaN,Incheon International Airport,Seoul,South Korea,ICN,RKSI,37.469101,126.450996,23,...,130,130,260,368,368,736,7,0.384644,0.428005,0.028143
1852,3797,NaN,John F Kennedy International Airport,New York,United States,JFK,KJFK,40.639801,-73.778900,13,...,160,162,322,455,456,911,7,0.397875,0.443024,0.026887
1783,3670,NaN,Dallas Fort Worth International Airport,Dallas-Fort Worth,United States,DFW,KDFW,32.896801,-97.038002,607,...,185,186,371,467,467,934,7,0.375328,0.421385,0.026800
1835,3751,NaN,Denver International Airport,Denver,United States,DEN,KDEN,39.861698,-104.672997,5431,...,167,168,335,373,360,733,8,0.351626,0.394647,0.026481
1251,2709,NaN,El Dorado International Airport,Bogota,Colombia,BOG,SKBO,4.701590,-74.146900,8361,...,74,74,148,155,152,307,7,0.332734,0.368554,0.025478
381,813,NaN,OR Tambo International Airport,Johannesburg,South Africa,JNB,FAOR,-26.139200,28.246000,5558,...,81,80,161,160,158,318,8,0.352138,0.388712,0.024291
1727,3550,NaN,George Bush Intercontinental Houston Airport,Houston,United States,IAH,KIAH,29.984400,-95.341400,97,...,168,169,337,242,243,485,7,0.380733,0.427197,0.023953
1900,3885,NaN,Suvarnabhumi Airport,Bangkok,Thailand,BKK,VTBS,13.681100,100.747002,5,...,120,120,240,329,325,654,8,0.366325,0.410867,0.023738
576,1229,NaN,Adolfo Suárez Madrid–Barajas Airport,Madrid,Spain,MAD,LEMD,40.471926,-3.562640,1998,...,156,158,314,331,330,661,8,0.382585,0.430723,0.023560

In [28]:
df1_sorted2 = df1_sorted.sort_values(by="outdegree", ascending=False)
outdegree_desc = df1_sorted2.reset_index(drop=True)
outdegree_desc[outdegree_desc["name"] == "Ted Stevens Anchorage International Airport" ] # ranking outdegree = 279, BC = 5
outdegree_desc[outdegree_desc["name"] == "Guarulhos - Governador André Franco Montoro International Airport" ] # ranking outdegree = 74, BC = 11
outdegree_desc[outdegree_desc["name"] == "Sydney Kingsford Smith International Airport" ] # ranking outdegree = 85, BC = 14
outdegree_desc[outdegree_desc["name"] == "Brisbane International Airport" ] # ranking outdegree = 145, BC = 16

,Id,Label,name,city,country,iata,icao,latitude,longitude,alt,...,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality
145,3320,NaN,Brisbane International Airport,Brisbane,Australia,BNE,YBBN,-27.384199,153.117004,13,...,55,59,114,143,151,294,8,0.329666,0.359612,0.03193

In [35]:
df1_sorted2 = df1_sorted.sort_values(by="outdegree", ascending=False)

In [52]:
# Step 1: Reset index so we can get rankings
df1_ranked = df1_sorted.reset_index(drop=True)
df2_ranked = df1_sorted2.reset_index(drop=True)

# Step 2: Add rankings to each DataFrame
df1_ranked['bc_rank'] = df1_ranked.index +1
df2_ranked['outdegree_rank'] = df2_ranked.index +1

# Step 3: Merge on 'name' to align the data
merged = pd.merge(
    df1_ranked[['name', 'city', 'bc_rank']],
    df2_ranked[['name', 'outdegree_rank']],
    on='name'
)

# Step 4: Calculate the absolute difference in rankings
merged['rank_diff'] = (merged['bc_rank'] - merged['outdegree_rank']).abs()

# Step 5: Sort by difference
final = merged.sort_values(by='bc_rank', ascending=True)

# (Optional) Reset index for neatness
final = final.reset_index(drop=True)

df_final = pd.DataFrame(final)
# Show the top rows
df_final.head(50)

,name,city,bc_rank,outdegree_rank,rank_diff
0,Charles de Gaulle International Airport,Paris,1,2,1
1,Los Angeles International Airport,Los Angeles,2,23,21
2,Dubai International Airport,Dubai,3,11,8
3,Frankfurt am Main Airport,Frankfurt,4,1,3
4,Ted Stevens Anchorage International Airport,Anchorage,5,280,275
5,Beijing Capital International Airport,Beijing,6,7,1
6,Chicago O'Hare International Airport,Chicago,7,6,1
7,Lester B. Pearson International Airport,Toronto,8,24,16
8,Amsterdam Airport Schiphol,Amsterdam,9,3,6
9,Atatürk International Airport,Istanbul,10,4,6
10,Guarulhos - Governador André Franco Montoro In...,Sao Paulo,11,74,63
11,London Heathrow Airport,London,12,12,0
12,Narita International Airport,Tokyo,13,58,45
13,Sydney Kingsford Smith International Airport,Sydney,14,86,72
14,Singapore Changi Airport,Singapore,15,42,27
15,Brisbane International Airport,Brisbane,16,146,130
16,Seattle Tacoma International Airport,Seattle,17,76,59
17,Hartsfield Jackson Atlanta International Airport,Atlanta,18,5,13
18,Domodedovo International Airport,Moscow,19,9,10
19,Hong Kong International Airport,Hong Kong,20,37,17
20,Montreal / Pierre Elliott Trudeau Internationa...,Montreal,21,72,51
21,Incheon International Airport,Seoul,22,38,16
22,John F Kennedy International Airport,New York,23,17,6
23,Dallas Fort Worth International Airport,Dallas-Fort Worth,24,10,14
24,Denver International Airport,Denver,25,14,11
25,El Dorado International Airport,Bogota,26,110,84
26,OR Tambo International Airport,Johannesburg,27,96,69
27,George Bush Intercontinental Houston Airport,Houston,28,13,15
28,Suvarnabhumi Airport,Bangkok,29,46,17
29,Adolfo Suárez Madrid–Barajas Airport,Madrid,30,18,12
30,Shanghai Pudong International Airport,Shanghai,31,22,9
31,Ninoy Aquino International Airport,Manila,32,103,71
32,Miami International Airport,Miami,33,35,2
33,Stockholm-Arlanda Airport,Stockholm,34,43,9
34,Vancouver International Airport,Vancouver,35,109,74
35,Kuala Lumpur International Airport,Kuala Lumpur,36,50,14
36,Hamad International Airport,Doha,37,48,11
37,Guangzhou Baiyun International Airport,Guangzhou,38,26,12
38,Soekarno-Hatta International Airport,Jakarta,39,133,94
39,Sheremetyevo International Airport,Moscow,40,29,11
40,Newark Liberty International Airport,Newark,41,21,20
41,Tokyo Haneda International Airport,Tokyo,42,113,71
42,Munich Airport,Munich,43,8,35
43,Faa'a International Airport,Papeete,44,352,308
44,Indira Gandhi International Airport,Delhi,45,67,22
45,Comodoro Arturo Merino Benítez International A...,Santiago,46,239,193
46,Auckland International Airport,Auckland,47,212,165
47,Licenciado Benito Juarez International Airport,Mexico City,48,71,23
48,Jorge Newbery Airpark,Buenos Aires,49,217,168
49,Copenhagen Kastrup Airport,Copenhagen,50,45,5

In [53]:
df_final[df_final["name"].isin([
    "Ted Stevens Anchorage International Airport",
    "Guarulhos - Governador André Franco Montoro International Airport",
    "Sydney Kingsford Smith International Airport"
])]

,name,city,bc_rank,outdegree_rank,rank_diff
4,Ted Stevens Anchorage International Airport,Anchorage,5,280,275
10,Guarulhos - Governador André Franco Montoro In...,Sao Paulo,11,74,63
13,Sydney Kingsford Smith International Airport,Sydney,14,86,72

In [59]:
df.groupby("country").count()

,Id,Label,name,city,iata,icao,latitude,longitude,alt,tz,...,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,4,0,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
Albania,1,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Algeria,26,0,26,26,26,26,26,26,26,26,...,26,26,26,26,26,26,26,26,26,26
American Samoa,1,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Angola,14,0,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,2,0,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Western Sahara,2,0,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Yemen,9,0,9,9,9,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
Zambia,7,0,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
Zimbabwe,3,0,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3

In [3]:
df_edges = pd.read_csv("Flights_Edges_notMerged.csv")
df_edges.head()

,Source,Target,Type,Id,Label,Weight,airline,aid,s,d,codeshare,stops,equipment
0,2965,2990,Directed,270652,NaN,1,2B,410,AER,KZN,NaN,0,CR2
1,2966,2990,Directed,270653,NaN,1,2B,410,ASF,KZN,NaN,0,CR2
2,2966,2962,Directed,270654,NaN,1,2B,410,ASF,MRV,NaN,0,CR2
3,2968,2990,Directed,270655,NaN,1,2B,410,CEK,KZN,NaN,0,CR2
4,2968,4078,Directed,270656,NaN,1,2B,410,CEK,OVB,NaN,0,CR2

In [4]:
df_edges.groupby("airline").count()

,Source,Target,Type,Id,Label,Weight,aid,s,d,codeshare,stops,equipment
airline,,,,,,,,,,,,
2B,40,40,40,40,0,40,40,40,40,0,40,40
2G,19,19,19,19,0,19,19,19,19,0,19,19
2I,18,18,18,18,0,18,18,18,18,0,18,18
2J,22,22,22,22,0,22,22,22,22,0,22,22
2K,12,12,12,12,0,12,12,12,12,0,12,12
...,...,...,...,...,...,...,...,...,...,...,...,...
ZH,797,797,797,797,0,797,797,797,797,400,797,797
ZI,64,64,64,64,0,64,64,64,64,0,64,64
ZK,53,53,53,53,0,53,53,53,53,0,53,53
ZL,88,88,88,88,0,88,88,88,88,0,88,88
ZM,4,4,4,4,0,4,4,4,4,0,4,4

In [5]:
df_nodes = pd.read_csv("Flights_Nodes_notMerged.csv")
df_nodes.head()

,Id,Label,name,city,country,iata,icao,latitude,longitude,alt,...,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality
0,1,NaN,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,...,5,5,10,5,5,10,9,0.228983,0.239638,0.000000
1,2,NaN,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,...,8,8,16,8,8,16,9,0.229033,0.240114,0.000001
2,3,NaN,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,...,12,10,22,12,10,22,9,0.229050,0.240273,0.000001
3,4,NaN,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,...,11,11,22,11,11,22,9,0.229067,0.240432,0.000001
4,5,NaN,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,...,47,48,95,47,48,95,8,0.296876,0.321212,0.013955

In [8]:
df_nodes_china = df_nodes.loc[df_nodes["country"] == "China"]
df_nodes_china #173 airports

,Id,Label,name,city,country,iata,icao,latitude,longitude,alt,...,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality
1628,3364,NaN,Beijing Capital International Airport,Beijing,China,PEK,ZBAA,40.080101,116.584999,116,...,530,531,1061,530,531,1061,7,0.389356,0.441109,0.057146
1629,3366,NaN,Dongshan Airport,Hailar,China,HLD,ZBLA,49.205002,119.824997,2169,...,18,18,36,18,18,36,8,0.281496,0.300333,0.000206
1630,3368,NaN,Tianjin Binhai International Airport,Tianjin,China,TSN,ZBTJ,39.124401,117.346001,10,...,145,145,290,145,145,290,8,0.292896,0.320870,0.000107
1631,3369,NaN,Taiyuan Wusu Airport,Taiyuan,China,TYN,ZBYN,37.746899,112.627998,2575,...,109,109,218,109,109,218,8,0.291918,0.318009,0.000024
1632,3370,NaN,Guangzhou Baiyun International Airport,Guangzhou,China,CAN,ZGGG,23.392401,113.299004,50,...,330,333,663,330,333,663,8,0.363489,0.407522,0.015153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3134,10160,NaN,Erenhot Saiwusu International Airport,Erenhot,China,ERL,ZBER,43.422500,112.096667,3301,...,2,2,4,2,2,4,8,0.280442,0.297764,0.000000
3136,10940,NaN,Zhangjiakou Ningyuan Airport,Zhangjiakou,China,ZQZ,ZBZJ,40.738602,114.930000,2347,...,2,2,4,2,2,4,9,0.220989,0.231133,0.000000
3137,10941,NaN,Arxan Yi'ershi Airport,Arxan,China,YIE,ZBES,47.310600,119.911700,2925,...,1,1,2,1,1,2,9,0.224330,0.234625,0.000000
3144,11473,NaN,Jinchuan Airport,Jinchuan,China,JIC,ZLJC,38.542222,102.348333,4740,...,6,6,12,6,6,12,9,0.231545,0.245423,0.000001
3145,11498,NaN,Alashankou Bole (Bortala) airport,Bole,China,BPL,ZWAX,44.895000,82.300000,1253,...,1,1,2,1,1,2,9,0.235092,0.247446,0.000000

In [13]:
# Get list of IATA codes for Chinese airports
china_airports = set(df_nodes_china['iata'])

# Filter edges where both source and destination are in China
china_domestic_flights = df_edges[
    (df_edges['s'].isin(china_airports)) &
    (df_edges['d'].isin(china_airports))
]

len(china_domestic_flights)

6851

In [17]:
df_nodes_merged_USA = df.loc[df["country"] == "United States"]
df_nodes_merged_USA

,Id,Label,name,city,country,iata,icao,latitude,longitude,alt,...,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,Eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality
1669,3411,NaN,Barter Island LRRS Airport,Barter Island,United States,BTI,PABA,70.134003,-143.582001,2,...,2,2,4,2,2,4,10,0.188654,0.194670,9.500000
1670,3414,NaN,Point Lay LRRS Airport,Point Lay,United States,PIZ,PPIZ,69.732903,-163.005005,22,...,1,1,2,1,1,2,10,0.188598,0.194389,0.000000
1671,3415,NaN,Hilo International Airport,Hilo,United States,ITO,PHTO,19.721399,-155.048004,38,...,3,3,6,4,4,8,8,0.285300,0.299329,0.000000
1672,3417,NaN,Bettles Airport,Bettles,United States,BTT,PABT,66.913902,-151.529007,647,...,3,3,6,4,4,8,9,0.212697,0.220058,1.500000
1673,3420,NaN,Fort Yukon Airport,Fort Yukon,United States,FYU,PFYU,66.571503,-145.250000,433,...,4,4,8,6,6,12,9,0.212754,0.220349,13002.830581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3054,8200,NaN,Toksook Bay Airport,Toksook Bay,United States,OOK,PAOO,60.541401,-165.087006,59,...,2,1,3,3,1,4,11,0.158801,0.162515,6289.000000
3070,8314,NaN,Hilton Head Airport,Hilton Head Island,United States,HHH,KHXD,32.224400,-80.697502,19,...,2,2,4,4,4,8,8,0.259550,0.274628,0.000000
3112,9543,NaN,Ogden Hinckley Airport,Ogden,United States,OGD,KOGD,41.195900,-112.012001,4473,...,1,1,2,1,1,2,10,0.208524,0.216741,0.000000
3113,9739,NaN,Napakiak Airport,Napakiak,United States,WNA,PANA,60.690300,-161.979004,17,...,1,1,2,1,1,2,11,0.158801,0.162515,3145.000000
3114,9744,NaN,Napaskiak Airport,Napaskiak,United States,PKA,PAPK,60.702900,-161.778000,24,...,1,1,2,1,1,2,10,0.188756,0.195067,3145.000000

In [19]:
len(df_nodes_merged_USA.loc[df_nodes_merged_USA["outdegree"] >= 50])

32

In [26]:
df_nodes_portugal = df_nodes.loc[df_nodes["country"] == "Portugal"]
df_nodes_brazil = df_nodes.loc[df_nodes["country"] == "Brazil"]

portugal_airports = set(df_nodes_portugal['iata'])
brazil_airports = set(df_nodes_brazil['iata'])

PTtoBR_flights = df_edges[
    (df_edges['s'].isin(portugal_airports)) &
    (df_edges['d'].isin(brazil_airports))
]

BRtoPT_flights = df_edges[
    (df_edges['s'].isin(brazil_airports)) &
    (df_edges['d'].isin(portugal_airports))
]

print(len(PTtoBR_flights)+len(BRtoPT_flights))

24

In [27]:
df_edges.head()

,Source,Target,Type,Id,Label,Weight,airline,aid,s,d,codeshare,stops,equipment
0,2965,2990,Directed,270652,NaN,1,2B,410,AER,KZN,NaN,0,CR2
1,2966,2990,Directed,270653,NaN,1,2B,410,ASF,KZN,NaN,0,CR2
2,2966,2962,Directed,270654,NaN,1,2B,410,ASF,MRV,NaN,0,CR2
3,2968,2990,Directed,270655,NaN,1,2B,410,CEK,KZN,NaN,0,CR2
4,2968,4078,Directed,270656,NaN,1,2B,410,CEK,OVB,NaN,0,CR2

In [31]:
df_airlines = pd.read_csv("airlines.csv")

In [35]:
import re
df_airlines.loc[df_airlines["Private flight"] == "Ryanair"]

         1 Private flight  \N   -  N/A Unnamed: 5 Unnamed: 6  Y
4288  4296        Ryanair  \N  FR  RYR    RYANAIR    Ireland  Y